name: quax
description: A private and clean way to browse Twitter/X

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 4.0.18+400001010

environment:
  sdk: ">=2.18.0 <3.0.0"

dependency_overrides:
  intl: ^0.17.0

dependencies:
  flutter:
    sdk: flutter

  # Core Flutter dependencies
  flutter_localizations:
    sdk: flutter

  # API & Networking
  http: ^1.2.1
  dart_twitter_api: # this is a fork which is up to date
    git: 
      url: https://github.com/Teskann/twitter_api.git

  # UI & Media
  auto_direction: ^0.0.6
  extended_image: ^10.0.0
  extended_nested_scroll_view: ^6.0.0
  infinite_scroll_pagination: ^4.0.0
  flutter_cache: ^0.1.0
  flutter_material_color_picker: ^1.2.0
  file_picker: ^10.3.6
  flutter_file_dialog: ^3.0.1
  flutter_iconpicker: ^4.0.1
  flutter_portal: ^1.1.4
  webview_flutter: ^4.13.0
  webview_cookie_manager_plus: ^2.0.16
  video_player: ^2.4.9

  # Localization & Styling
  intl: any
  flutter_localized_locales: ^2.0.3
  dynamic_color: ^1.7.0

  # State Management & Data
  pref: ^2.7.0
  provider: ^6.0.4
  flutter_triple: ^3.0.0
  multi_select_flutter: ^4.1.3

  # Utilities & Helpers
  crypto: ^3.0.3
  html_unescape: ^2.0.0
  logging: ^1.1.0
  measure_size: ^4.0.0
  package_info_plus: ^8.3.0
  path: ^1.8.2
  path_provider: ^2.0.11
  permission_handler: ^12.0.0+1
  quiver: ^3.1.0
  scroll_to_index: ^3.0.1
  secure_content: ^1.0.1
  share_plus: ^10.1.4
  sqflite: ^2.2.2
  sqflite_common: ^2.4.0+2
  sqflite_migration_plan: ^1.0.0
  timeago: ^3.3.0
  app_links: ^6.4.0
  url_launcher: ^6.1.7
  uuid: ^4.3.3
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.2.4

  # Miscellaneous
  async_button_builder: ^3.0.0+1
  chewie: ^1.13.0
  ffcache: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3
  flutter_lints:
  flutter_oss_licenses: ^3.0.2
  intl_utils: ^2.8.1
  sqflite_common_ffi: ^2.2.0+1

flutter_icons:
  android: "launcher_icon"
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material icons font is
  # included with your application, so that you can use the icons in
  # the material icons class.
  uses-material-design: true

  assets:
    - assets/icon.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  generate: true

flutter_intl:
  enabled: true
  class_name: L10n
