name: New version

on:
  workflow_dispatch:
    inputs:
      major:
        description: "Major version number"
        required: true
        type: string
      minor:
        description: "Minor version number"
        required: true
        type: string
      patch:
        description: "Patch version number"
        required: true
        type: string

permissions:
  contents: write
  actions: write   # needed to dispatch other workflows

jobs:
  bump-version:
    name: Bump pubspec version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compute version
        id: version
        run: |
          VERSION="${{ github.event.inputs.major }}.${{ github.event.inputs.minor }}.${{ github.event.inputs.patch }}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Get current codeNumber from pubspec.yaml
        id: get_codeNumber
        run: |
          current_codeNumber=$(grep -oP 'version: \d+\.\d+\.\d+\+\K\d+' pubspec.yaml || echo 0)
          echo "Current codeNumber is: $current_codeNumber"
          new_codeNumber=$((current_codeNumber + 1))
          echo "New codeNumber is: $new_codeNumber"
          echo "NEW_CODE_NUMBER=$new_codeNumber" >> $GITHUB_ENV

      - name: Update version in pubspec.yaml
        run: |
          echo "Updating pubspec.yaml to version: $VERSION+${{ env.NEW_CODE_NUMBER }}"
          if grep -q '^version:' pubspec.yaml; then
            sed -i "s/^version:.*/version: $VERSION+${{ env.NEW_CODE_NUMBER }}/" pubspec.yaml
          else
            echo "version: $VERSION+${{ env.NEW_CODE_NUMBER }}" >> pubspec.yaml
          fi
          grep '^version:' pubspec.yaml

      - name: Generate changelog
        run: |
          ./generate-release-notes.sh $VERSION

      - name: Commit and tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pubspec.yaml changelog.md
          git commit -m "Bumping to version $VERSION"
          git tag "v$VERSION"
          git push origin HEAD:master
          git push origin "v$VERSION"
